message(STATUS "Building benches...")

#add_executable(tfhe_bootstrapping tfhe_bootstrapping.cpp)
#add_executable(bench_blindrotate bench_blindrotate.cpp)
#add_executable(bench_blindrotate_ternary bench_blindrotate_ternary.cpp)
#add_executable(bench_blindrotate_ternary_noise bench_blindrotate_ternary_noise.cpp)
#add_executable(bench_thread bench_thread.cpp)
#add_executable(benchmarkCRT benchMCRT.cpp)
#add_executable(swap_copy swap_copy.cpp)
#add_executable(mod_mult mod_mult.cpp)
#add_executable(crt crt.cpp)
#add_executable(mod_red mod_red.cpp)
#
#target_link_libraries(tfhe_bootstrapping PRIVATE yatfhe_lib)
#target_link_libraries(bench_blindrotate PRIVATE yatfhe_lib)
#target_link_libraries(bench_blindrotate_ternary PRIVATE yatfhe_lib)
#target_link_libraries(bench_blindrotate_ternary_noise PRIVATE yatfhe_lib)
#target_link_libraries(bench_thread PRIVATE yatfhe_lib)
#target_link_libraries(benchmarkCRT PRIVATE yatfhe_lib)
#target_link_libraries(swap_copy PRIVATE yatfhe_lib)
#target_link_libraries(mod_mult PRIVATE yatfhe_lib)
#target_link_libraries(crt PRIVATE yatfhe_lib)
#target_link_libraries(mod_red PRIVATE yatfhe_lib)

file(GLOB YA_BENCHMARK_SOURCES *.cpp)

foreach(bench_source ${YA_BENCHMARK_SOURCES})
    get_filename_component(target_name ${bench_source} NAME_WE)
    add_executable(${target_name} ${bench_source})
    target_include_directories(${target_name} PRIVATE ${CMAKE_SOURCE_DIR}/yatfhe/include)
    target_link_libraries(${target_name} PRIVATE yatfhe_lib)

endforeach()

message(STATUS "Building benches...DONE!!")
